# Generated by Django 4.0.2 on 2022-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
